### ISSUE TITLE
Limitation du compteur des heures de recuperation

### ISSUE THREAD

**Issue by Lolaru84** [libertempo/web#450]
[Bug] Pour nous aider à corriger le bug dans les meilleures conditions, merci de prendre le temps de détailler ces quelques points
Système et application

    Système d'exploitation :Ubuntu 16.04.1
    Serveur HTTP et version :apache2.4.18
    Version MySQL et PHP : 5.0.12 et php 7.0.15
    Navigateur et version :Firefox 54.0
    Version de l'application :1.9.3
    Avez-vous des notifications dans la console du navigateur : non
    Avez-vous des erreurs dans le log du serveur http (ex : /var/log/apache2) :
    Oui mais rien qui soit lié

Reproduction du bug

    Prérequis : synchronisation avec un annuaire AD 2012
    Action de déclenchement : ajout d'heures supplémentaires
    Résultat attendu : positionner le solde voulu
    Résultat constaté : Impossible d'aller au delà de 23h59, sinon il faut convertir en jours et heures, ce qui n'est pas le même usage.

**Comment by Prytoegrian** [comment]
Quel serait le comportement que tu voudrais *au delà de bien positionner le solde* ?
* Peut-on dépasser les 24h de « dette » ?
* Est-ce-qu'il faut continuer à utiliser un timepicker ?

Comment tu verrais la fonctionnalité « gestion des heures » en gros, peut-être qu'on a proposé une solution pour les heures qui n'est pas adapté.

**Comment by wouldsmina** [comment]
@Lolaru84 timepicker == menu déroulant permettant de sélectionner une heure ou une durée.

**Comment by jmv42** [comment]
Je pense qu'il serai souhaitable de conserver un comptage en heures et de lever la limite de 23h59

**Comment by prytoegrian** [comment]
J'espère que vous me pardonnerez, je fais le ménage de tous les tickets qui sont antérieurs au 29/03/18. Croyez bien que c'est pas par plaisir, mais nous sommes littéralement en train de nous noyer. Nous avons une sincère envie de bien faire et c'est pour ça que nous avons traîné à le faire : nous avons réellement envie de vous aider à tirer parti au mieux de LT. Aussi, c'est un crève cœur de clôturer comme une brute, mais nous ne pouvons pas étudier toutes les demandes, débattre, prioriser, faire les devs, les tester, faire de la com' et faciliter la vie aux contributeurs. Nous sommes trop peu et nous avons besoin de nous y prendre plus intelligemment.

Alors je prends mes responsabilités, pour assurer l'avenir de LT ; je suis disposé à répondre à toute question sur [la mailing list](http://libertempo.tuxfamily.org/mailing-list/).

Nous ne vous laissons pas sans rien, nous avons mis en place un outil pour rapporter des bugs, proposer des améliorations ou aider à prioriser en votant pour les contributions d'autrui : https://feedback.libertempo.fr/
J'estime que les sujets importants reviendront sur le tapis et grâce à ce nouvel outil, nous saurons les adresser plus facilement.

Merci de votre compréhension.

**Comment by jmv42** [comment]
Pas de soucis je comprend. D'autant plus que cette limitation sur les heures supp. a disparue je ne sais pas comment. Merci pour votre travail Envoyé depuis mon smartphone Samsung Galaxy.
-------- Message d'origine --------De : Prytoegrian <notifications@github.com> Date : 29/03/2019  20:38  (GMT+01:00) À : libertempo/web <web@noreply.github.com> Cc : jmv42 <jean-marc.virat@st-etienne.archi.fr>, Manual <manual@noreply.github.com> Objet : Re: [libertempo/web] Limitation du compteur des heures de recuperation (#450) J'espère que vous me pardonnerez, je fais le ménage de tous les tickets qui sont antérieurs au 29/03/18. Croyez bien que c'est pas par plaisir, mais nous sommes littéralement en train de nous noyer. Nous avons une sincère envie de bien faire et c'est pour ça que nous avons traîné à le faire : nous avons réellement envie de vous aider à tirer parti au mieux de LT. Aussi, c'est un crève cœur de clôturer comme une brute, mais nous ne pouvons pas étudier toutes les demandes, débattre, prioriser, faire les devs, les tester, faire de la com' et faciliter la vie aux contributeurs. Nous sommes trop peu et nous avons besoin de nous y prendre plus intelligemment.

Alors je prends mes responsabilités, pour assurer l'avenir de LT ; je suis disposé à répondre à toute question sur la mailing list.

Nous ne vous laissons pas sans rien, nous avons mis en place un outil pour rapporter des bugs, proposer des améliorations ou aider à prioriser en votant pour les contributions d'autrui : https://feedback.libertempo.fr/

J'estime que les sujets importants reviendront sur le tapis et grâce à ce nouvel outil, nous saurons les adresser plus facilement.

Merci de votre compréhension.



—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/libertempo/web","title":"libertempo/web","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/libertempo/web"}},"updates":{"snippets":[{"icon":"PERSON","message":"@prytoegrian in #450: J'espère que vous me pardonnerez, je fais le ménage de tous les tickets qui sont antérieurs au 29/03/18. Croyez bien que c'est pas par plaisir, mais nous sommes littéralement en train de nous noyer. Nous avons une sincère envie de bien faire et c'est pour ça que nous avons traîné à le faire : nous avons réellement envie de vous aider à tirer parti au mieux de LT. Aussi, c'est un crève cœur de clôturer comme une brute, mais nous ne pouvons pas étudier toutes les demandes, débattre, prioriser, faire les devs, les tester, faire de la com' et faciliter la vie aux contributeurs. Nous sommes trop peu et nous avons besoin de nous y prendre plus intelligemment.\r\n\r\nAlors je prends mes responsabilités, pour assurer l'avenir de LT ; je suis disposé à répondre à toute question sur [la mailing list](http://libertempo.tuxfamily.org/mailing-list/).\r\n\r\nNous ne vous laissons pas sans rien, nous avons mis en place un outil pour rapporter des bugs, proposer des améliorations ou aider à prioriser en votant pour les contributions d'autrui : https://feedback.libertempo.fr/\r\nJ'estime que les sujets importants reviendront sur le tapis et grâce à ce nouvel outil, nous saurons les adresser plus facilement.\r\n\r\nMerci de votre compréhension."}],"action":{"name":"View Issue","url":"https://github.com/libertempo/web/issues/450#issuecomment-478124828"}}}

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/libertempo/web/issues/450#issuecomment-478124828",

"url": "https://github.com/libertempo/web/issues/450#issuecomment-478124828",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]
